### ISSUE TITLE
Integrating naxsi in opnsense

### ISSUE THREAD

**Issue by Vivekmauli14** [wargio/naxsi#138]
Hii,

I am interested in integrating OWASP principles into my OPNsense firewall setup with naxsi. Specifically, I am looking for advice or best practices on how to:

./Implement rules or configurations in OPNsense that align with OWASP recommendations.
./Utilize OPNsense features or plugins to mitigate the risks identified in the OWASP Top 10.
./Leverage any available tools or scripts that facilitate the incorporation of OWASP security measures in OPNsense.
./Set up logging and monitoring within OPNsense to detect and respond to the security threats outlined by OWASP.

Thanks in advance.

Br,
Vivek

**Comment by wargio** [comment]
i think opnsense has a package for [naxsi](https://docs.opnsense.org/manual/how-tos/nginx_waf.html)

That said i don't know how it is configured (since normally i configure NAXSI manually and not via a UI).

To set it up for your NGINX server you can use the opnsense package and manually add any rule that might be needed by your web application.

For a manual setup, you can check this example: https://github.com/wargio/naxsi/issues/134#issuecomment-2041120247

Besides the main rule, you can also integrate these extra rules https://github.com/wargio/naxsi/tree/main/naxsi_rules/blocking manually or by importing the file with the nginx directive `include`.

**Comment by wargio** [comment]
beware that learning mode is preferred at the beginning to patch any false positive and then can be removed to block the requests.

For the logs, naxsi logs are written in the error logger of NGINX thus, you can just forward the logs to a syslog server and display them in whatever way you like. i strongly suggest to enable the json logs.

**Comment by Vivekmauli14** [comment]
Hi,

Thank you for your response. I have successfully imported all the other rules. Could you please confirm if this setup will cover the OWASP Top 10 security risks?

Additionally, would it be possible to include the Core Rule Set in the WAF plugin? 
(https://github.com/coreruleset)

I want to integrate ModSecurity into the WAF to ensure I'm protected with OWASP Top 10 security mitigations. I'd appreciate your guidance if there are any specific configurations you recommend for enhanced security.

Thank you again for your assistance.

**Comment by wargio** [comment]
it might. the owasp top 10 changes each year and some vulns are unrelated to what the waf can do.

**Comment by Vivekmauli14** [comment]
right, considering this only we would like the modesec rules to be included, though it might not be directly related to WAF as you said, despite that we would like to include these rules in Nginx, as per OWASP principles.
Kindly guide me or point me on the right direction.

Thanks

**Comment by wargio** [comment]
i just want to point out that also the modesec rules does not cover the owasp.

**Comment by Vivekmauli14** [comment]
Thanks, @wargio for your insights on this, In case you can suggest the best rulesets to achieve OWASP top 10 Threat integration which can be integrated with Nginx on OPNsense.

Best,
Vivek

**Comment by wargio** [comment]
I'm sorry but this is out of scope for NAXSI.

As explained before, OWASP vulnerabilities are a set of generic vulnerabilities that are used to classify the actual vulnerabilities.
Using just a WAF to be "protected" against the top 10 OWASP is meaningless.

Let me make an example using this list: https://owasp.org/www-project-top-ten/

- **A01:2021-Broken Access Control** this *could* be mitigated by having a WAF rule to block any traffic to a specific resource by whitelisting only a subset of values.
- **A02:2021-Cryptographic Failures** unrelated and unpatchable unless the vulnerability is linked to an exposed resource.
- **A03:2021-Injection** this is a classic and indeed the WAF can be used to virtual patch (i.e. patch without touching the actual vulnerable code) the vulnerability via a rule.
- **A04:2021-Insecure Design** this *could* be mitigated by having a WAF rule but most of the time it does not.
- **A05:2021-Security Misconfiguration** this is a classic and indeed the WAF can be used to virtual patch.
- **A06:2021-Vulnerable and Outdated Components** this *could* be mitigated by having a WAF rule.
- **A07:2021-Identification and Authentication Failures** unrelated and unpatchable via WAF.
- **A08:2021-Software and Data Integrity Failures** unrelated and unpatchable via WAF.
- **A09:2021-Security Logging and Monitoring Failures** unrelated and unpatchable via WAF.
- **A10:2021-Server-Side Request Forgery** this *could* be mitigated using a WAF (NAXSI does not have this capability since it is stateless), but usually is strongly suggested to implement this on the actual code.
