### ISSUE TITLE
HTML request body checks with a blacklist/whitelist

### ISSUE THREAD

**Issue by staticlibs** [wargio/naxsi#43]
This is an idea for a possible feature that can be added to NAXSI. When request body contains HTML, currently it is possible to check it with regexes using `rx` rules or check it for XSS with Libinjection. The latter will tokenize HTML and will apply the heuristics and tags/attributes blacklists. This Libinjection XSS check appeared to be a bit too coarse - the blacklists of tags and attributes are hardcoded and heuristics is quite basic.

The idea is to allow to specify the blacklist/whitelist for tags and attributes in Nginx config file. Then to use HTML5 tokenization to iterate over the tags/attributes, apply configured blacklist/whitelist to them and record the results into `$LIBINJECTION_HTML5` variable (analogous to `$LIBINJENCTION_XSS` one):

```
    h5_state_t h5;
    libinjection_h5_init(&h5, s, len, (enum html5_flags) flags);
    while (libinjection_h5_next(&h5)) {
        if (h5.token_type == TAG_NAME_OPEN) {
            if (is_black_tag(h5.token_start, h5.token_len)) {
                // increment $LIBINJECTION_HTML5 here;
            }
        } else if (h5.token_type == ATTR_NAME) {
        [...]
```

When `h5.token_type` is `DATA_TEXT`, it can contain unparsed HTML passed inside the outer XML, example:

```
    <?xml version="1.0" encoding="UTF-8"?>
    <items>
      <item>
        <description>
          <![CDATA[Foo Bar Description<div id="a"><p><iframe src="javascript&#58;alert('Hello XSS')">]]>
        </description>
        <id><![CDATA[944ba0f3-bd5d-4b11-8cb9-31c4f3691bed]]></id>
      </item>
    </items>
```

In this case the whole string `Foo Bar Description<div id="a"><p><iframe src="javascript&#58;alert('Hello XSS')">` is treated as a `DATA_TEXT` token. The idea is to check such tokens for `<` symbol and to apply the HTML tokenization and filtering to them recursively while `<` symbol is there.

Such feature should be relatively straightforward to implement and may be useful for more fine tuned XSS detection.

Note, my employer does not have the dev budget for this task (if they would have had any budget - they would just have used some managed cloud WAF instead of Naxsi), so if I proceed with the implementation it can take a few weeks. Though, if implemented, such feature will be used in production, currently the subpar version of the above logic is implemented inside the target web app.

**Comment by wargio** [comment]
i think is is not the correct approach to the issue. XSS are annoying because the coder didn't use the proper way to embed values dynamically within the HTML.
The only solution to this issue is input validation. just create custom rules to allow only certain characters to be accepted.

Normally rules `1302` and `1303` are enough to block many XSS
https://github.com/wargio/naxsi/blob/main/naxsi_rules/naxsi_core.rules#L75-L76

side note: naxsi is being used by many many websites due it's low memory fingerprint by many companies; i even saw some chinese routers having it.

**Comment by staticlibs** [comment]
Thanks for your comments! I understand what XSS is, but I am nowhere near the expert in XSS detection, so any input on this is highly appreciated.

To explain the use case more, the target web app uses HTML extensively for parts of its functionality. So the user-edited HTML snippets can be stored in DB and can be returned back to client and be rendered in a web-browser in the same context where the main web page is displayed. It is not clear whether such HTML usage is a good idea (definitely not security-wise), but changing something about the HTML usage in the app is not feasible at this point.

To have some control over the contents of stored HTML, blacklists/whitelists for tags and attributes are used. So the balance between the functionality (which HTML features to allow) and security can be tuned in app settings. This approach seems to be effective because [common XSS examples](https://cheatsheetseries.owasp.org/cheatsheets/XSS_Filter_Evasion_Cheat_Sheet.html) seem to rely on a relatively narrow set of tags/attributes.

At the same time, being able to configure blacklist/whitelist contents is a hard requirement, the following input:

```
    <?xml version="1.0" encoding="UTF-8"?>
    <items>
      <item>
        <id><![CDATA[944ba0f3-bd5d-4b11-8cb9-31c4f3691bed]]></id>
        <description>
          <![CDATA[Foo Bar Description]]>
        </description>
        <template1>
          <![CDATA[<html><head><style>.cl1 {color: red;}</style></head><body><span class="cl1">ID: {{id}}</span></body></html>]]>
        </template1>
      </item>
    </items>
```

may or may not be allowed depending on application settings, whether the `<style>` tag is whitelisted or not.


Naxsi core rules do not seem to be suitable for this, because HTML5 tokenization is required to apply blacklists/whitelists. But Libinjection's XSS detection appeared to do almost what is needed - its [existing implementation](https://github.com/libinjection/libinjection/blob/88f0faa849995ef6aafa32a9da32eaca38a213c8/src/libinjection_xss.c#L414) checks the tags and attributes blacklists. But these blacklists [are hardcoded](https://github.com/libinjection/libinjection/blob/88f0faa849995ef6aafa32a9da32eaca38a213c8/src/libinjection_xss.c#L185) and cannot be configured.

So the idea was to add to Naxsi some kind of a custom `libinjection_xss()` implementation that:

1. Can be configured in Naxsi rules (Nginx conf) files, - this seems to be easy, as `NGX_CONF_1MORE` conf options should allow to define multiline lists in Nginx config 

2. Can "go deeper" with tokenization, - this seems to be doable, applying tokenization recursively on `DATA_TEXT` tokens will cover the XML wrapper case above (treating XML as HTML5 for tokenization seems to work fine). For JSON requests (likely a common case) - every input can be tried as a JSON first. If JSON parsing is successful, then parsed JSON tree can be iterated over and HTML5 tokenization and checks be applied to JSON field values. If JSON parsing failed - assume "XML or plaintext" case and just apply tokenization to the whole request

3. Can understand URL and HTML entity encodings, - this seems to be doable by applying the URL decoding once and the HTML decoding repeatedly (until all entities are decoded)

4. Uses the existing machinery for storing the detection results, introducing additional `$LIBINJECTION_HTML5` variable similar to `$LIBINJECTION_XSS` and `$LIBINJECTION_SQL` ones


Hopefully the above explains the idea better. It doesn't mean that Naxsi itself is an appropriate place for this functionality, just the `libinjection_xss()` implementation, how it is used in Naxsi, appeared to be very close to what is needed (still cannot be used in its current form due to hardcoded blacklists and heuristics).


PS: will ask here, just to not create a separate issue - I would like to add minor changes to the log parsing in `nxapi` (basically make GeoIP optional and make it run on python3 out of the box). Just the [main repo](https://github.com/nbs-system/nxapi-ng) seems to be unmaintained. Can you approve upcoming `nxapi` PRs to this main repo? Or can you fork it to your account, or maybe to create a `naxsi` github organization and move both Naxsi itself and the maintained version of `nxapi` there?

**Comment by wargio** [comment]
The main problem is that you are trying to virtual patch something that actually requires a proper patch on the software side.
The question you should ask yourself is: 
Where is this being used?

1. If it is used by admins only, then block the access to the method globally and whitelist the ip/cidr ranges from where the admins connects to, so they can submit the content changes via what it looks like a POST request.
2. If it is like a form used by anybody in the internet, you have various choices which ranges from allow only certain tags to allow only simple text.

Now depending on the scenario you have to understand which type of vulnerability is going to be exploited via the stored XSS and the risk associated with it.
If your client really think that they do not have the money to patch it, then you should tell them how much it costs to not patch such vulnerability which may impact their business revenue or even worse the security of their infra if the XSS steals some cookie or authentication header from an admin.

XSS are very hard to block and i do not think there are any sort of WAF that can 100% block them all.
actually from what i have seen in my years of working experience they all sucks (including naxsi) at blocking XSS since there are so many ways (often with small changes) to bypass them.

Regarding nxapi, i wanted to port it to py3 in its own repository.
If you are setting up a kibana like dashboard, i can sugges you to NOT use nxapi, but instead do something much simpler (which is my current setup)

`Nginx` > `logstash` > `elastic search` > `kibana`

If you want i can share with you my configuration of these and probably start writing the wiki with these infos

**Comment by staticlibs** [comment]
> The main problem is that you are trying to virtual patch something that actually requires a proper patch on the software side.

I think this describes the situation correctly. I will close this issue for now.

> Regarding nxapi, i wanted to port it to py3 in its own repository.
> If you are setting up a kibana like dashboard

No, not a dashboard, just wanted to be able to load a log file into SQLite. Will hold my (incomplete) changes to nxapi for now, will be able to cleanup and submit it to the nxapi repo when appropriate.
